/**
 * Barrel re-export: assembles the unified `api` object from domain modules.
 * Consumers import `api` (and types/utilities) from here.
 */

// --- Domain modules ---
import { authApi } from './auth';
import { usersApi, profilesApi } from './users';
import { guildsApi } from './guilds';
import { channelsApi } from './channels';
import { messagesApi, searchApi, threadsApi, invitesApi, filesApi } from './messages';
import { voiceApi } from './voice';
import { themesApi } from './themes';
import {
  communityShopApi,
  economyApi,
  relationshipsApi,
  groupDmsApi,
  messageRequestsApi,
  bugReportsApi,
  shopApi,
  inventoryApi,
  auctionsApi,
  marketplaceApi,
  botApplicationsApi,
  interactionsApi,
  wikiApi,
  eventsApi,
  pollsApi,
  scheduledMessagesApi,
  leaderboardApi,
  cosmeticsApi,
  botStoreApi,
  botInstallsApi,
  webhooksApi,
  adminTeamApi,
  adminAuditApi,
  adminBotStoreApi,
  feedbackApi,
  reportsApi,
  adminPortalsApi,
  telemetryApi,
  notificationsApi,
  bookmarksApi,
  workflowsApi,
  fameApi,
  stageApi,
  stickersApi,
  pushApi,
  reactionRolesApi,
  stickyMessagesApi,
  remindersApi,
  starboardApi,
  autoRolesApi,
  showcaseApi,
  friendshipStreaksApi,
  interestTagsApi,
  greetingCardsApi,
  textReactionsApi,
  timelineApi,
  ticketsApi,
  giveawaysApi,
  onboardingApi,
  guildLogApi,
  guildDigestApi,
  musicRoomsApi,
  whiteboardsApi,
  moodBoardApi,
  photoAlbumsApi,
  voiceEffectsApi,
  studyRoomsApi,
  questsApi,
  formsApi,
  confessionsApi,
  encryptionApi,
  federationApi,
  profileVisitorsApi,
  friendActivityApi,
  activityFeedApi,
  dailySpinApi,
  bundlePurchaseApi,
  tradesApi,
  channelDocumentsApi,
  dailyChallengesApi,
  welcomeScreenApi,
  giftsApi,
  collectibleCardsApi,
  capabilitiesApi,
  storiesApi,
  emojisApi,
  draftsApi,
  mutesApi,
  channelNotifPrefsApi,
  wordFilterApi,
  oauthAppsApi,
  referralsApi,
  banAppealsApi,
  genericApi,
  spamConfigApi,
  soundboardApi,
  guildBackupApi,
  modQueueApi,
  guildHighlightsApi,
  vanityProfileApi,
  auditLogEntriesApi,
  wordFilterTestApi,
  // Phase 6: Productivity
  calendarsApi,
  fileManagerApi,
  meetingSchedulerApi,
  todoListsApi,
  integrationsApi,
  botFrameworkApi,
  standupApi,
  timezoneApi,
  afkApi,
  playlistsApi,
  // Phase 7: Gamification
  xpApi,
  loginRewardsApi,
  userTitlesApi,
  quizzesApi,
  reputationApi,
  seasonalEventsApi,
  guildQuestsApi,
  profileBackgroundApi,
  // Wave 26: Cutting-edge features
  spatialRoomsApi,
  channelPresenceApi,
  ephemeralPodsApi,
  voiceReactionsApi,
  focusSessionsApi,
  channelBookmarksApi,
  messageComponentsApi,
  guildDigestGenerateApi,
  threadDashboardApi,
  notificationSoundsApi,
  ambientRoomsApi,
  p2pTransferApi,
  serverStatusApi,
  scheduleCalendarApi,
  readingListsApi,
  channelFollowingApi,
  calendarSyncApi,
  messageTranslateApi,
} from './misc';

// --- Re-export core utilities & errors ---
export { API_BASE, setAccessToken, getAccessToken, ApiRequestError, RateLimitError, apiFetch, buildQuery, refreshAccessToken } from './_core';

// --- Re-export types ---
export type {
  AuthResponse,
  RegisterRequest,
  LoginRequest,
  ApiError,
  KeysetPaginationParams,
  Guild,
  Channel,
  Message,
  GuildMember,
  Thread,
  GuildEmoji,
  ShopItem,
  InventoryItem,
  InviteInfo,
  SearchMessagesResponse,
  ClientTelemetryEvent,
  CommunityShopItem,
  CurrencyWallet,
  CurrencyLedgerEntry,
  BetaBugReport,
  BetaBugReportInboxItem,
  Role,
  Invite,
  Notification,
  UserSummary,
  UserStatus,
  ReactionGroup,
} from './_core';

export type { AvatarDecoration, ProfileEffect, Nameplate, PresenceStatus } from './_core';

export type { ThemeItem } from './themes';

// --- Assembled api object (matches original shape) ---
export const api = {
  capabilities: capabilitiesApi,
  auth: authApi,
  users: usersApi,
  profiles: profilesApi,
  communityShop: communityShopApi,
  economy: economyApi,
  voice: voiceApi,
  guilds: guildsApi,
  channels: channelsApi,
  messages: messagesApi,
  search: searchApi,
  threads: threadsApi,
  invites: invitesApi,
  files: filesApi,
  relationships: relationshipsApi,
  groupDms: groupDmsApi,
  messageRequests: messageRequestsApi,
  bugReports: bugReportsApi,
  shop: shopApi,
  inventory: inventoryApi,
  auctions: auctionsApi,
  marketplace: marketplaceApi,
  botApplications: botApplicationsApi,
  interactions: interactionsApi,
  wiki: wikiApi,
  events: eventsApi,
  polls: pollsApi,
  scheduledMessages: scheduledMessagesApi,
  leaderboard: leaderboardApi,
  themes: themesApi,
  cosmetics: cosmeticsApi,
  botStore: botStoreApi,
  botInstalls: botInstallsApi,
  webhooks: webhooksApi,
  adminTeam: adminTeamApi,
  adminAudit: adminAuditApi,
  adminBotStore: adminBotStoreApi,
  feedback: feedbackApi,
  reports: reportsApi,
  adminPortals: adminPortalsApi,
  telemetry: telemetryApi,
  notifications: notificationsApi,
  bookmarks: bookmarksApi,
  workflows: workflowsApi,
  fame: fameApi,
  stage: stageApi,
  stickers: stickersApi,
  push: pushApi,
  reactionRoles: reactionRolesApi,
  stickyMessages: stickyMessagesApi,
  reminders: remindersApi,
  starboard: starboardApi,
  autoRoles: autoRolesApi,
  showcase: showcaseApi,
  friendshipStreaks: friendshipStreaksApi,
  interestTags: interestTagsApi,
  greetingCards: greetingCardsApi,
  textReactions: textReactionsApi,
  timeline: timelineApi,
  tickets: ticketsApi,
  giveaways: giveawaysApi,
  onboarding: onboardingApi,
  guildLog: guildLogApi,
  guildDigest: guildDigestApi,
  musicRooms: musicRoomsApi,
  whiteboards: whiteboardsApi,
  moodBoard: moodBoardApi,
  photoAlbums: photoAlbumsApi,
  voiceEffects: voiceEffectsApi,
  studyRooms: studyRoomsApi,
  quests: questsApi,
  forms: formsApi,
  confessions: confessionsApi,
  encryption: encryptionApi,
  federation: federationApi,
  profileVisitors: profileVisitorsApi,
  friendActivity: friendActivityApi,
  activityFeed: activityFeedApi,
  dailySpin: dailySpinApi,
  bundlePurchase: bundlePurchaseApi,
  trades: tradesApi,
  channelDocuments: channelDocumentsApi,
  dailyChallenges: dailyChallengesApi,
  welcomeScreen: welcomeScreenApi,
  gifts: giftsApi,
  collectibleCards: collectibleCardsApi,
  stories: storiesApi,
  emojis: emojisApi,
  drafts: draftsApi,
  mutes: mutesApi,
  channelNotifPrefs: channelNotifPrefsApi,
  wordFilter: wordFilterApi,
  oauthApps: oauthAppsApi,
  referrals: referralsApi,
  banAppeals: banAppealsApi,
  spamConfig: spamConfigApi,
  soundboard: soundboardApi,
  guildBackup: guildBackupApi,
  modQueue: modQueueApi,
  guildHighlights: guildHighlightsApi,
  vanityProfile: vanityProfileApi,
  auditLogEntries: auditLogEntriesApi,
  wordFilterTest: wordFilterTestApi,
  // Phase 6: Productivity
  calendars: calendarsApi,
  fileManager: fileManagerApi,
  meetingScheduler: meetingSchedulerApi,
  todoLists: todoListsApi,
  integrations: integrationsApi,
  botFramework: botFrameworkApi,
  standup: standupApi,
  timezone: timezoneApi,
  afk: afkApi,
  playlists: playlistsApi,
  // Phase 7: Gamification
  xp: xpApi,
  loginRewards: loginRewardsApi,
  userTitles: userTitlesApi,
  quizzes: quizzesApi,
  reputation: reputationApi,
  seasonalEvents: seasonalEventsApi,
  guildQuests: guildQuestsApi,
  profileBackground: profileBackgroundApi,
  // Wave 26: Cutting-edge features
  spatialRooms: spatialRoomsApi,
  channelPresence: channelPresenceApi,
  ephemeralPods: ephemeralPodsApi,
  voiceReactions: voiceReactionsApi,
  focusSessions: focusSessionsApi,
  channelBookmarks: channelBookmarksApi,
  messageComponents: messageComponentsApi,
  guildDigestGenerate: guildDigestGenerateApi,
  threadDashboard: threadDashboardApi,
  notificationSounds: notificationSoundsApi,
  ambientRooms: ambientRoomsApi,
  p2pTransfer: p2pTransferApi,
  serverStatus: serverStatusApi,
  scheduleCalendar: scheduleCalendarApi,
  readingLists: readingListsApi,
  channelFollowing: channelFollowingApi,
  calendarSync: calendarSyncApi,
  messageTranslate: messageTranslateApi,
  get: genericApi.get,
  post: genericApi.post,
  patch: genericApi.patch,
  delete: genericApi.delete,
  put: genericApi.put,
};
