/**
 * Barrel re-export: assembles the unified `api` object from domain modules.
 * Consumers import `api` (and types/utilities) from here.
 */

// --- Domain modules ---
import { authApi } from './auth';
import { usersApi, profilesApi } from './users';
import { guildsApi } from './guilds';
import { channelsApi } from './channels';
import { messagesApi, searchApi, threadsApi, invitesApi, filesApi } from './messages';
import { voiceApi } from './voice';
import { themesApi } from './themes';
import {
  communityShopApi,
  economyApi,
  relationshipsApi,
  groupDmsApi,
  messageRequestsApi,
  bugReportsApi,
  shopApi,
  inventoryApi,
  auctionsApi,
  marketplaceApi,
  botApplicationsApi,
  interactionsApi,
  wikiApi,
  eventsApi,
  pollsApi,
  scheduledMessagesApi,
  leaderboardApi,
  cosmeticsApi,
  botStoreApi,
  botInstallsApi,
  webhooksApi,
  adminTeamApi,
  adminAuditApi,
  adminBotStoreApi,
  feedbackApi,
  reportsApi,
  adminPortalsApi,
  telemetryApi,
  notificationsApi,
  bookmarksApi,
  workflowsApi,
  fameApi,
  stageApi,
  stickersApi,
  pushApi,
  reactionRolesApi,
  stickyMessagesApi,
  remindersApi,
  starboardApi,
  autoRolesApi,
  showcaseApi,
  friendshipStreaksApi,
  interestTagsApi,
  greetingCardsApi,
  textReactionsApi,
  timelineApi,
  ticketsApi,
  giveawaysApi,
  onboardingApi,
  guildLogApi,
  guildDigestApi,
  musicRoomsApi,
  whiteboardsApi,
  moodBoardApi,
  photoAlbumsApi,
  voiceEffectsApi,
  studyRoomsApi,
  questsApi,
  formsApi,
  confessionsApi,
  encryptionApi,
  federationApi,
  profileVisitorsApi,
  friendActivityApi,
  activityFeedApi,
  dailySpinApi,
  bundlePurchaseApi,
  tradesApi,
  channelDocumentsApi,
  dailyChallengesApi,
  welcomeScreenApi,
  giftsApi,
  collectibleCardsApi,
  capabilitiesApi,
  genericApi,
} from './misc';

// --- Re-export core utilities & errors ---
export { API_BASE, setAccessToken, getAccessToken, ApiRequestError, RateLimitError, apiFetch, buildQuery, refreshAccessToken } from './_core';

// --- Re-export types ---
export type {
  AuthResponse,
  RegisterRequest,
  LoginRequest,
  ApiError,
  CursorPaginationParams,
  Guild,
  Channel,
  Message,
  GuildMember,
  Thread,
  GuildEmoji,
  ShopItem,
  InventoryItem,
  InviteInfo,
  SearchMessagesResponse,
  ClientTelemetryEvent,
  CommunityShopItem,
  CurrencyWallet,
  CurrencyLedgerEntry,
  BetaBugReport,
  BetaBugReportInboxItem,
} from './_core';

export type { AvatarDecoration, ProfileEffect, Nameplate, PresenceStatus } from './_core';

// --- Assembled api object (matches original shape) ---
export const api = {
  capabilities: capabilitiesApi,
  auth: authApi,
  users: usersApi,
  profiles: profilesApi,
  communityShop: communityShopApi,
  economy: economyApi,
  voice: voiceApi,
  guilds: guildsApi,
  channels: channelsApi,
  messages: messagesApi,
  search: searchApi,
  threads: threadsApi,
  invites: invitesApi,
  files: filesApi,
  relationships: relationshipsApi,
  groupDms: groupDmsApi,
  messageRequests: messageRequestsApi,
  bugReports: bugReportsApi,
  shop: shopApi,
  inventory: inventoryApi,
  auctions: auctionsApi,
  marketplace: marketplaceApi,
  botApplications: botApplicationsApi,
  interactions: interactionsApi,
  wiki: wikiApi,
  events: eventsApi,
  polls: pollsApi,
  scheduledMessages: scheduledMessagesApi,
  leaderboard: leaderboardApi,
  themes: themesApi,
  cosmetics: cosmeticsApi,
  botStore: botStoreApi,
  botInstalls: botInstallsApi,
  webhooks: webhooksApi,
  adminTeam: adminTeamApi,
  adminAudit: adminAuditApi,
  adminBotStore: adminBotStoreApi,
  feedback: feedbackApi,
  reports: reportsApi,
  adminPortals: adminPortalsApi,
  telemetry: telemetryApi,
  notifications: notificationsApi,
  bookmarks: bookmarksApi,
  workflows: workflowsApi,
  fame: fameApi,
  stage: stageApi,
  stickers: stickersApi,
  push: pushApi,
  reactionRoles: reactionRolesApi,
  stickyMessages: stickyMessagesApi,
  reminders: remindersApi,
  starboard: starboardApi,
  autoRoles: autoRolesApi,
  showcase: showcaseApi,
  friendshipStreaks: friendshipStreaksApi,
  interestTags: interestTagsApi,
  greetingCards: greetingCardsApi,
  textReactions: textReactionsApi,
  timeline: timelineApi,
  tickets: ticketsApi,
  giveaways: giveawaysApi,
  onboarding: onboardingApi,
  guildLog: guildLogApi,
  guildDigest: guildDigestApi,
  musicRooms: musicRoomsApi,
  whiteboards: whiteboardsApi,
  moodBoard: moodBoardApi,
  photoAlbums: photoAlbumsApi,
  voiceEffects: voiceEffectsApi,
  studyRooms: studyRoomsApi,
  quests: questsApi,
  forms: formsApi,
  confessions: confessionsApi,
  encryption: encryptionApi,
  federation: federationApi,
  profileVisitors: profileVisitorsApi,
  friendActivity: friendActivityApi,
  activityFeed: activityFeedApi,
  dailySpin: dailySpinApi,
  bundlePurchase: bundlePurchaseApi,
  trades: tradesApi,
  channelDocuments: channelDocumentsApi,
  dailyChallenges: dailyChallengesApi,
  welcomeScreen: welcomeScreenApi,
  gifts: giftsApi,
  collectibleCards: collectibleCardsApi,
  get: genericApi.get,
  post: genericApi.post,
  patch: genericApi.patch,
  delete: genericApi.delete,
  put: genericApi.put,
};
