/**
 * channels.ts — Drizzle ORM schemas for channel tables.
 *
 * This file defines two tables:
 *
 *   1. `channels`          — Every text/voice/category channel in a guild, and
 *                            every DM or group DM between users, lives here.
 *                            A nullable `guild_id` differentiates guild channels
 *                            from direct-message channels.
 *
 *   2. `dm_channel_members` — Join table that records which users are
 *                             participants in a DM or GROUP_DM channel.
 *                             Not used for guild channels (guild membership
 *                             controls access there instead).
 *
 * Channel types:
 *   GUILD_TEXT     — Text channel inside a guild (messages, threads).
 *   GUILD_VOICE    — Voice channel inside a guild (WebRTC sessions).
 *   GUILD_CATEGORY — Container used to group other guild channels; it has no
 *                    messages of its own. Child channels point to it via parentId.
 *   DM             — A private 1-to-1 conversation between two users.
 *   GROUP_DM       — A private conversation with up to N users (no guild).
 *
 * Design notes:
 *   - `guildId` is nullable because DM and GROUP_DM channels have no guild.
 *     Application code enforces the invariant that GUILD_* types always have a
 *     guildId, and DM/GROUP_DM types always have guildId = null.
 *   - `parentId` self-references channels.id with `onDelete: 'set null'` so
 *     that deleting a category doesn't cascade-delete all its child channels —
 *     they just become uncategorised (parentId = null).
 *   - `rateLimitPerUser` (slowmode) is stored in seconds. 0 = no slowmode.
 */

import {
  pgTable,
  uuid,
  varchar,
  text,
  integer,
  boolean,
  timestamp,
  unique,
} from 'drizzle-orm/pg-core';
import { guilds } from './guilds';
import { users } from './users';

// ---------------------------------------------------------------------------
// channels
// ---------------------------------------------------------------------------

/**
 * The `channels` table.
 *
 * Unified table for all channel types: guild text/voice/category channels and
 * direct-message channels. The `type` column drives behaviour differences;
 * columns that don't apply to a given type are left null by convention.
 */
export const channels = pgTable('channels', {
  /**
   * Primary key. Generated by Postgres, never by the application.
   */
  id: uuid('id').primaryKey().defaultRandom(),

  /**
   * The guild this channel belongs to. Null for DM and GROUP_DM channels.
   * Cascades on delete — when a guild is deleted all its channels are removed.
   */
  guildId: uuid('guild_id').references(() => guilds.id, { onDelete: 'cascade' }),

  /**
   * Display name of the channel (e.g. "general", "announcements").
   * For DM channels the name is typically derived client-side from the other
   * participant's displayName, but a value is still required here.
   */
  name: varchar('name', { length: 100 }).notNull(),

  /**
   * Discriminator for channel behaviour.
   *
   * Valid values:
   *   GUILD_TEXT     — Standard text channel in a guild.
   *   GUILD_VOICE    — Voice/video channel in a guild.
   *   GUILD_CATEGORY — Organising container; no messages of its own.
   *   DM             — One-to-one direct message channel.
   *   GROUP_DM       — Multi-user direct message channel (no guild).
   */
  type: varchar('type', { length: 30 }).notNull(),

  /**
   * Optional description / topic shown in the channel header.
   * Typically used for GUILD_TEXT channels. Null for voice channels and DMs.
   */
  topic: text('topic'),

  /**
   * Display ordering of the channel within its parent (guild or category).
   * Lower values appear first. The application keeps these contiguous but
   * gaps are harmless — the UI sorts by this value ascending.
   */
  position: integer('position').notNull().default(0),

  /**
   * Parent category channel ID. Used to nest GUILD_TEXT and GUILD_VOICE
   * channels under a GUILD_CATEGORY. Null means the channel is at the
   * top level of the guild.
   *
   * Uses `onDelete: 'set null'` so that deleting a category un-nests its
   * children rather than deleting them along with it.
   */
  parentId: uuid('parent_id').references((): any => channels.id, { onDelete: 'set null' }),

  /**
   * Whether this channel is age-restricted (Not Safe For Work).
   * Users must explicitly confirm their age to view NSFW channels.
   * Defaults to false.
   */
  isNsfw: boolean('is_nsfw').notNull().default(false),

  /**
   * Slowmode setting in seconds. 0 = disabled. When > 0, a user must wait
   * this many seconds between messages in this channel. Enforced server-side.
   */
  rateLimitPerUser: integer('rate_limit_per_user').notNull().default(0),

  /**
   * Background image/video URL set by channel admins via the Set Theme button.
   * Stored as a full URL pointing to /api/v1/files/<id>.
   */
  backgroundUrl: text('background_url'),

  /**
   * Media type of the background — 'image' or 'video'.
   * Null when no background is set.
   */
  backgroundType: varchar('background_type', { length: 10 }),

  /**
   * Timestamp of channel creation.
   */
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),

  /**
   * Timestamp of the last modification (name, topic, position change, etc.).
   * Updated by the application on any channel settings change.
   */
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * TypeScript type for a fetched channel row.
 */
export type Channel = typeof channels.$inferSelect;

/**
 * TypeScript type for inserting a new channel row.
 */
export type NewChannel = typeof channels.$inferInsert;

// ---------------------------------------------------------------------------
// dm_channel_members
// ---------------------------------------------------------------------------

/**
 * The `dm_channel_members` table.
 *
 * Tracks which users are participants in a DM or GROUP_DM channel. This table
 * is NOT used for guild channels — guild membership (guild_members) governs
 * access to those.
 *
 * For a standard DM this table will always have exactly two rows per channel.
 * For a GROUP_DM it may have two or more.
 *
 * The unique constraint on (channel_id, user_id) prevents a user from being
 * added to the same DM channel twice and enables fast "is this user a
 * participant?" lookups in authorization middleware.
 */
export const dmChannelMembers = pgTable(
  'dm_channel_members',
  {
    /**
     * Surrogate primary key for the participation record.
     */
    id: uuid('id').primaryKey().defaultRandom(),

    /**
     * The DM or GROUP_DM channel this record belongs to.
     * Cascades on delete — removing a channel cleans up all participant rows.
     */
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),

    /**
     * The user who is a participant in this DM channel.
     * Cascades on delete — removing a user account removes them from all DMs.
     */
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
  },
  (table) => [
    /**
     * Each user can only be a participant in a given DM channel once.
     */
    unique('dm_channel_members_channel_id_user_id_key').on(table.channelId, table.userId),
  ],
);

/**
 * TypeScript type for a fetched dm_channel_members row.
 */
export type DmChannelMember = typeof dmChannelMembers.$inferSelect;

/**
 * TypeScript type for inserting a new dm_channel_members row.
 */
export type NewDmChannelMember = typeof dmChannelMembers.$inferInsert;
