/**
 * files.ts — Drizzle ORM schema for the `files` table.
 *
 * Tracks every file uploaded through the Gratonite API: user avatars, guild
 * icons/banners, and message attachments. A single table covers all upload
 * types — the purpose of a file is inferred from where its ID is referenced
 * (e.g., users.avatar_hash, guilds.icon_hash, messages.attachments).
 *
 * Design notes:
 *
 *   uploaderId — set null on delete:
 *     If the user who uploaded a file deletes their account, the file record
 *     is retained but uploaderId becomes null. Guild icons, banners, and
 *     historical message attachments must remain accessible even after their
 *     original uploader is gone. Cascade-deleting files on user deletion would
 *     break guilds that the user created assets for and other users' chat
 *     history.
 *
 *   storageKey — unique, used as the canonical reference:
 *     The storage key is the path on disk or the S3 object key. It is unique
 *     to prevent two rows from pointing at the same file on the backend storage
 *     system. The application can use storageKey to delete the underlying
 *     object when cleaning up orphaned files.
 *
 *   url — public CDN / static URL:
 *     Stored alongside storageKey so that API responses can return a ready-to-use
 *     URL without a runtime computation. If the CDN base URL changes, a
 *     one-time data migration is needed — this trade-off is acceptable for
 *     simplicity at this stage.
 *
 *   size — in bytes:
 *     Stored for quota enforcement, display in the UI ("2.4 MB"), and
 *     server-side validation. Integer is sufficient for files up to ~2 GB;
 *     use bigint if very large files need to be supported.
 */

import {
  pgTable,
  uuid,
  varchar,
  integer,
  timestamp,
} from 'drizzle-orm/pg-core';
import { users } from './users';

// ---------------------------------------------------------------------------
// files
// ---------------------------------------------------------------------------

/**
 * The `files` table.
 *
 * Central registry of all files uploaded to the platform. Referenced by
 * other tables (users, guilds, messages) via their hash/ID fields.
 */
export const files = pgTable('files', {
  /**
   * Primary key. Generated by Postgres, never by the application.
   * This UUID is used as the "hash" / file ID referenced by other tables
   * (e.g., users.avatar_hash = files.id).
   */
  id: uuid('id').primaryKey().defaultRandom(),

  /**
   * The user who uploaded this file.
   *
   * Uses `onDelete: 'set null'` so that files (guild icons, historical
   * attachments) remain accessible after the uploader's account is deleted.
   * Null indicates the original uploader no longer has an account.
   */
  uploaderId: uuid('uploader_id').references(() => users.id, { onDelete: 'set null' }),

  /**
   * Original filename as provided by the client at upload time.
   * Stored for display in the UI (e.g., "screenshot.png" in the attachment
   * viewer). Not used as a path on the storage backend.
   */
  filename: varchar('filename', { length: 255 }).notNull(),

  /**
   * MIME type of the file, e.g. "image/png", "video/mp4", "application/pdf".
   * Determined server-side via magic byte inspection (not trusted from the
   * client). Used by the API to set the correct Content-Type header when
   * serving the file and to enforce upload type restrictions.
   */
  mimeType: varchar('mime_type', { length: 100 }).notNull(),

  /**
   * File size in bytes. Used for quota tracking and display in the UI.
   * An integer column supports files up to ~2.1 GB; extend to bigint if
   * larger uploads are ever needed.
   */
  size: integer('size').notNull(),

  /**
   * Path on disk or S3 object key for the file. Unique across all records
   * so that two rows never point at the same backend object.
   * The application uses this to read, serve, or delete the file from storage.
   * Example (local): "uploads/2024/01/abc123.png"
   * Example (S3):    "gratonite/uploads/abc123.png"
   */
  storageKey: varchar('storage_key', { length: 500 }).notNull().unique(),

  /**
   * Publicly accessible URL for this file (CDN or static server path).
   * Returned directly in API responses so clients do not need to compute
   * the URL themselves. If the CDN base changes, update this column via
   * a migration.
   * Example: "https://cdn.gratonite.com/uploads/abc123.png"
   */
  url: varchar('url', { length: 500 }).notNull(),

  /**
   * Timestamp of when the file was uploaded to the platform.
   */
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * TypeScript type for a fetched file row.
 */
export type File = typeof files.$inferSelect;

/**
 * TypeScript type for inserting a new file row.
 */
export type NewFile = typeof files.$inferInsert;
