/**
 * group-encryption.ts — Drizzle ORM schema for group E2E encryption key storage.
 *
 * Stores per-channel symmetric group keys, encrypted individually for each
 * member using their ECDH public key. Supports key versioning so that when
 * membership changes a new key version can be distributed.
 */

import { pgTable, uuid, integer, jsonb, timestamp } from 'drizzle-orm/pg-core';
import { channels } from './channels';

// ---------------------------------------------------------------------------
// group_encryption_keys
// ---------------------------------------------------------------------------

/**
 * The `group_encryption_keys` table.
 *
 * Each row represents one version of the symmetric AES-GCM group key for a
 * GROUP_DM channel. The `keyData` column is a JSON object mapping userId →
 * base64-encoded encrypted key (the group key wrapped with the member's ECDH
 * public key via an ephemeral ECDH exchange).
 *
 * Multiple rows per channel are allowed to support key rotation; the client
 * always fetches the latest version (highest `version` number) where its own
 * userId appears in `keyData`.
 */
export const groupEncryptionKeys = pgTable('group_encryption_keys', {
  /**
   * Primary key. Generated by Postgres, never by the application.
   */
  id: uuid('id').primaryKey().defaultRandom(),

  /**
   * The GROUP_DM channel this key belongs to.
   * Cascades on delete — removing a channel removes all its key versions.
   */
  channelId: uuid('channel_id')
    .notNull()
    .references(() => channels.id, { onDelete: 'cascade' }),

  /**
   * Monotonically increasing key version. Version 1 is the initial key.
   * Incremented when membership changes and a new key is distributed.
   */
  version: integer('version').notNull(),

  /**
   * Map of userId → base64-encoded encrypted group key.
   * Each member's copy of the group key is encrypted with that member's
   * ECDH public key using an ephemeral key exchange so the server never
   * sees the plaintext group key.
   */
  keyData: jsonb('key_data').notNull(),

  /** Row creation timestamp. */
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type GroupEncryptionKey = typeof groupEncryptionKeys.$inferSelect;
export type NewGroupEncryptionKey = typeof groupEncryptionKeys.$inferInsert;
