/**
 * guilds.ts — Drizzle ORM schemas for guild (server) tables.
 *
 * This file defines two tables:
 *
 *   1. `guilds`        — A guild (a.k.a. "server") is the top-level container
 *                        for channels, members, roles, and other resources.
 *                        Every guild has exactly one owner.
 *
 *   2. `guild_members` — Join table associating users with guilds. A user must
 *                        have a row here to access a guild's content. Also
 *                        stores per-guild metadata like nickname.
 *
 * Design notes:
 *   - `memberCount` is a denormalized counter kept in sync by the application
 *     on join/leave events. This avoids a COUNT(*) query on every guild card
 *     render. A DB trigger could also maintain it, but triggers complicate
 *     migrations; the app-level approach is kept for portability.
 *   - `iconHash` / `bannerHash` store file IDs (CDN keys) rather than full
 *     URLs so that the CDN base URL can change without a data migration.
 *   - `onDelete: 'restrict'` on ownerId means you cannot delete a user who
 *     still owns a guild — they must transfer ownership first. This prevents
 *     ownerless ghost guilds.
 */

import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  integer,
  timestamp,
  unique,
} from 'drizzle-orm/pg-core';
import { users } from './users';

// ---------------------------------------------------------------------------
// guilds
// ---------------------------------------------------------------------------

/**
 * The `guilds` table.
 *
 * Represents a community server — the root namespace for channels, roles, and
 * members. Analogous to a "server" in Discord or a "workspace" in Slack.
 */
export const guilds = pgTable('guilds', {
  /**
   * Primary key. Generated by Postgres, never by the application.
   */
  id: uuid('id').primaryKey().defaultRandom(),

  /**
   * Display name of the guild, shown everywhere in the UI.
   * Limited to 100 characters; must be non-empty.
   */
  name: varchar('name', { length: 100 }).notNull(),

  /**
   * Optional long-form description of the guild's purpose or topic.
   * Shown in discovery listings and on the guild's invite page.
   */
  description: text('description'),

  /**
   * File ID (CDN storage key) for the guild's icon image.
   * Null until the owner uploads one. The client constructs the full URL
   * using the CDN base URL + this hash.
   */
  iconHash: varchar('icon_hash', { length: 255 }),

  /**
   * File ID (CDN storage key) for the guild's banner image.
   * Displayed as a wide header on the guild's discovery/invite page.
   * Null until the owner uploads one.
   */
  bannerHash: varchar('banner_hash', { length: 255 }),

  /**
   * Optional guild-level accent color (hex) used by clients for branding.
   * Example: "#526df5".
   */
  accentColor: varchar('accent_color', { length: 20 }),

  /**
   * The user who owns this guild. Ownership confers all permissions and the
   * ability to delete the guild.
   *
   * Uses `onDelete: 'restrict'` — you cannot delete a user account while they
   * still own guilds. The owner must transfer ownership first (application
   * logic) before the account can be removed.
   */
  ownerId: uuid('owner_id')
    .notNull()
    .references(() => users.id, { onDelete: 'restrict' }),

  /**
   * Whether this guild appears in the public discovery listing.
   * Defaults to false (private/invite-only). The owner can opt in.
   */
  isDiscoverable: boolean('is_discoverable').notNull().default(false),
  isFeatured: boolean('is_featured').notNull().default(false),
  isPinned: boolean('is_pinned').notNull().default(false),
  discoverRank: integer('discover_rank').notNull().default(9999),

  /**
   * Denormalized count of current members. Updated by the application on
   * member join (increment) and leave/kick/ban (decrement). Avoids an
   * expensive COUNT(*) on `guild_members` for every guild list render.
   * Starts at 1 because the creator is the first member.
   */
  memberCount: integer('member_count').notNull().default(1),

  /**
   * Category for discovery filtering.
   * One of: gaming|music|art|tech|community|anime|education|other (nullable).
   */
  category: varchar('category', { length: 30 }),

  /**
   * Timestamp of guild creation. Set once by Postgres, never changed.
   */
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),

  /**
   * Timestamp of the last modification to this row (name, description, icon,
   * etc.). Updated in application code on every guild settings change.
   */
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * TypeScript type for a fully-hydrated guild row (SELECT *).
 */
export type Guild = typeof guilds.$inferSelect;

/**
 * TypeScript type for inserting a new guild row.
 */
export type NewGuild = typeof guilds.$inferInsert;

// ---------------------------------------------------------------------------
// guild_members
// ---------------------------------------------------------------------------

/**
 * The `guild_members` table.
 *
 * Join table that records which users belong to which guilds. A user must
 * have a row here to be considered a member of the guild — without it, they
 * cannot see the guild's channels or send messages.
 *
 * Additional per-membership data (nickname, join date) lives here rather than
 * on the user row, since both values are scoped to a specific guild.
 *
 * The unique constraint on (guild_id, user_id) prevents duplicate membership
 * rows and serves as a natural index for "is this user in this guild?" lookups.
 */
export const guildMembers = pgTable(
  'guild_members',
  {
    /**
     * Surrogate primary key for the membership record.
     */
    id: uuid('id').primaryKey().defaultRandom(),

    /**
     * The guild this membership belongs to.
     * Cascades on delete — when a guild is deleted all member records
     * are automatically removed; no orphan rows.
     */
    guildId: uuid('guild_id')
      .notNull()
      .references(() => guilds.id, { onDelete: 'cascade' }),

    /**
     * The user who is a member of the guild.
     * Cascades on delete — when a user account is deleted, all of their
     * guild memberships are automatically removed.
     */
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),

    /**
     * Optional per-guild nickname. If set, this is shown instead of the
     * user's global displayName within the guild. Null means "use the global
     * display name".
     */
    nickname: varchar('nickname', { length: 64 }),

    /**
     * When the user joined the guild. Displayed in the member info panel.
     */
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    /**
     * A user can only be a member of each guild once.
     * Also used by the "is member?" check in authorization middleware.
     */
    unique('guild_members_guild_id_user_id_key').on(table.guildId, table.userId),
  ],
);

/**
 * TypeScript type for a fetched guild_members row.
 */
export type GuildMember = typeof guildMembers.$inferSelect;

/**
 * TypeScript type for inserting a new guild_members row.
 */
export type NewGuildMember = typeof guildMembers.$inferInsert;
