/**
 * messages.ts — Drizzle ORM schema for the `messages` table.
 *
 * Every user-sent message in any channel (guild text channel, DM, or group DM)
 * is stored here. A single table handles all channel types; the `channel_id`
 * foreign key determines which conversation a message belongs to.
 *
 * Design notes:
 *
 *   authorId — set null on delete (NOT cascade):
 *     When a user account is deleted we preserve their messages so that
 *     conversations remain coherent for other participants. The author becomes
 *     a "Deleted User" in the UI (detected by authorId = null). Cascade-deleting
 *     messages on user deletion would silently destroy shared conversation
 *     history that other users depend on.
 *
 *   attachments — stored as JSONB:
 *     File references are embedded directly in the message row as a JSON array
 *     rather than a separate `message_attachments` table. This avoids a JOIN
 *     on every message fetch. The schema for each element is:
 *       { id, url, filename, size, mimeType }
 *     The `files` table is still the source of truth for upload metadata;
 *     `attachments` here is a denormalized snapshot at send time so that
 *     messages remain readable even if a file record is later purged.
 *
 *   content nullable:
 *     A message that consists only of attachments has no text content.
 *     Storing null is more accurate than storing an empty string and lets
 *     the API distinguish "no content" from "empty string" unambiguously.
 *
 *   Index on (channel_id, created_at DESC):
 *     Messages are almost always fetched paginated within a single channel,
 *     sorted newest-first or oldest-first. This composite index makes both
 *     directions fast. Drizzle does not generate this automatically from the
 *     table definition — it must be added in the migration SQL or via
 *     `.index()` in the table definition. It is declared below using the
 *     Drizzle `index` helper so drizzle-kit includes it in the generated SQL.
 */

import {
  pgTable,
  uuid,
  text,
  jsonb,
  boolean,
  timestamp,
  index,
} from 'drizzle-orm/pg-core';
import { channels } from './channels';
import { users } from './users';

// ---------------------------------------------------------------------------
// messages
// ---------------------------------------------------------------------------

/**
 * The `messages` table.
 *
 * Stores every message sent across the platform. Both guild channel messages
 * and DM messages share this table; the channel type on the referenced
 * `channels` row determines the context.
 */
export const messages = pgTable(
  'messages',
  {
    /**
     * Primary key. Generated by Postgres, never by the application.
     */
    id: uuid('id').primaryKey().defaultRandom(),

    /**
     * The channel this message was sent in.
     * Cascades on delete — when a channel is deleted all its messages go too.
     * This is the expected behaviour: deleting a channel permanently removes
     * its history.
     */
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),

    /**
     * The user who wrote this message.
     *
     * Uses `onDelete: 'set null'` (NOT cascade). When a user account is
     * deleted, their messages remain but authorId becomes null. The API
     * renders these as sent by "Deleted User". This preserves conversation
     * integrity for other participants.
     */
    authorId: uuid('author_id').references(() => users.id, { onDelete: 'set null' }),

    /**
     * The text body of the message. Null for attachment-only messages.
     * Clients should sanitize before rendering to prevent XSS. The server
     * does not strip HTML — it stores whatever the client sends and relies
     * on the client-side renderer to handle it safely.
     */
    content: text('content'),

    /**
     * JSON array of file attachments included with this message.
     * Each element has the shape:
     *   { id: string, url: string, filename: string, size: number, mimeType: string }
     * Defaults to an empty array for messages with no attachments.
     * Stored as a denormalized snapshot so messages remain readable even if
     * the corresponding `files` row is later purged.
     */
    attachments: jsonb('attachments').notNull().default([]),

    /**
     * Whether this message has been edited at least once after sending.
     * The UI displays an "edited" indicator when this is true.
     */
    edited: boolean('edited').notNull().default(false),

    /**
     * Timestamp of the most recent edit. Null until the message is first
     * edited. Set by the application on every successful edit operation.
     */
    editedAt: timestamp('edited_at', { withTimezone: true }),

    /** ID of the message this is replying to. Null if not a reply. */
    replyToId: uuid('reply_to_id'),

    /** Thread ID if this message is part of a thread. Null for normal messages. */
    threadId: uuid('thread_id'),

    /**
     * Timestamp of when the message was originally sent.
     * Used as the cursor for keyset / cursor-based pagination.
     */
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),

    /**
     * Optional expiry timestamp for disappearing messages.
     * Null means the message never expires. When set, a background cron job
     * deletes the message after this time and emits MESSAGE_DELETE.
     * Set at creation time based on the channel's `disappearTimer` setting.
     */
    expiresAt: timestamp('expires_at', { withTimezone: true }),
  },
  (table) => [
    /**
     * Composite index to accelerate per-channel message queries.
     *
     * The vast majority of message reads are:
     *   SELECT * FROM messages WHERE channel_id = $1 ORDER BY created_at DESC LIMIT 50
     * (and variants with a cursor for pagination). This index satisfies those
     * queries with an index-only scan on channel_id + created_at, avoiding a
     * full sequential scan of the messages table.
     */
    index('messages_channel_id_created_at_idx').on(table.channelId, table.createdAt),
  ],
);

/**
 * TypeScript type for a fully-hydrated message row (SELECT *).
 */
export type Message = typeof messages.$inferSelect;

/**
 * TypeScript type for inserting a new message row.
 */
export type NewMessage = typeof messages.$inferInsert;
