/**
 * users.ts — Drizzle ORM schema for the `users` table.
 *
 * This is the central user record for Gratonite. It stores both authentication
 * fields (email, passwordHash) and profile/presence fields (displayName,
 * avatarHash, status, etc.) in a single table for simplicity at this stage of
 * the project. If profile data grows significantly it can be split out later.
 *
 * Column naming convention:
 *   - TypeScript property uses camelCase.
 *   - The actual Postgres column name is snake_case (declared via the second
 *     argument to each column builder, e.g. varchar('display_name')).
 *   - Drizzle handles the mapping automatically.
 *
 * Why uuid primary keys?
 *   UUIDs prevent enumeration attacks (sequential integer IDs leak how many
 *   users exist) and are safe to expose in API responses.
 *
 * Why gen_random_uuid()?
 *   Postgres's built-in function — no extension required in Postgres 13+. The
 *   application never has to generate the ID itself, which keeps insert logic
 *   simple and avoids collisions.
 */

import { pgTable, uuid, varchar, text, boolean, jsonb, timestamp } from 'drizzle-orm/pg-core';

/**
 * The `users` table.
 *
 * Every account on Gratonite has exactly one row here. Servers, channels,
 * messages, and other resources all reference `users.id`.
 */
export const users = pgTable('users', {
  /**
   * Primary key. Generated by Postgres, never by the application.
   */
  id: uuid('id').primaryKey().defaultRandom(),

  /**
   * The unique handle a user chooses, e.g. "alice_99".
   * Limited to 32 chars; must be globally unique case-insensitively
   * (enforced in application logic — a lower-case index can be added later).
   */
  username: varchar('username', { length: 32 }).notNull().unique(),

  /**
   * The user's email address, used for login and verification.
   * Stored lower-cased at write time in application logic.
   */
  email: varchar('email', { length: 255 }).notNull().unique(),

  /**
   * Argon2id hash of the user's password. Never stored in plain text.
   * The argon2 library produces its own encoded string that includes the
   * algorithm, parameters, salt, and hash — so this single column contains
   * everything needed to verify a password.
   */
  passwordHash: varchar('password_hash', { length: 255 }).notNull(),

  /**
   * The name shown in the UI, separate from the login username.
   * Users can change this freely without affecting their login handle.
   */
  displayName: varchar('display_name', { length: 64 }).notNull(),

  /**
   * File ID (CDN key / storage hash) for the user's avatar image.
   * Null until the user uploads one. The client constructs the full URL
   * from this ID using the CDN base URL.
   */
  avatarHash: varchar('avatar_hash', { length: 255 }),

  /**
   * File ID for the user's profile banner image (the wide banner shown on
   * their profile card, similar to Discord's banner feature).
   * Null until the user uploads one.
   */
  bannerHash: varchar('banner_hash', { length: 255 }),

  /**
   * Free-text bio shown on the user's profile. No formatting enforced here —
   * clients should sanitize before rendering.
   */
  bio: text('bio'),

  /**
   * Optional pronouns string, e.g. "she/her", "they/them". Max 50 chars.
   */
  pronouns: varchar('pronouns', { length: 50 }),

  /**
   * A short custom status message, e.g. "Coding something cool 🚀".
   * Distinct from `status` (presence); this is user-set free text.
   */
  customStatus: varchar('custom_status', { length: 128 }),

  /**
   * Presence / availability status.
   * Valid values: 'online' | 'idle' | 'dnd' | 'invisible'
   * Defaults to 'online'. The server or client updates this via the
   * presence system (Socket.IO). 'invisible' means the user appears offline
   * to others but can still see all content.
   */
  status: varchar('status', { length: 20 }).notNull().default('online'),

  /**
   * Whether the user has admin privileges on the platform.
   * True only for Gratonite staff / instance owners.
   * This is NOT the same as server-level admin roles (those live in a
   * separate permissions system).
   */
  isAdmin: boolean('is_admin').notNull().default(false),

  /**
   * Whether the user has verified their email address.
   */
  emailVerified: boolean('email_verified').notNull().default(false),

  /** MFA TOTP secret — encrypted. Null if MFA not set up. */
  mfaSecret: varchar('mfa_secret', { length: 255 }),

  /** Whether MFA is currently enabled for this user. */
  mfaEnabled: boolean('mfa_enabled').notNull().default(false),

  /** Whether the user has completed onboarding. */
  onboardingCompleted: boolean('onboarding_completed').notNull().default(false),

  /** Name style displayed on messages (rainbow, fire, ice, gold, glitch, none). */
  nameplateStyle: text('nameplate_style').default('none'),

  /** User badges (e.g. admin, early_adopter, verified, developer, moderator, supporter). */
  badges: text('badges').array().default([]),

  /** User interests from onboarding, stored as JSON array of strings. */
  interests: text('interests'),

  /** Rich presence activity (e.g. playing a game). */
  activity: jsonb('activity'),

  /** Custom status emoji. */
  statusEmoji: text('status_emoji'),

  /** When the custom status expires. Null = no expiry. */
  statusExpiresAt: timestamp('status_expires_at', { withTimezone: true }),

  /**
   * Timestamp of account creation. Set once by Postgres default, never
   * updated by the application.
   */
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),

  /**
   * Timestamp of the last modification to this row. Updated manually in
   * application code on any profile or auth change (not via a trigger, to
   * keep the DB portable).
   */
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * TypeScript type for a fully-hydrated user row (SELECT *).
 * Use this as the return type for functions that fetch complete user records.
 */
export type User = typeof users.$inferSelect;

/**
 * TypeScript type for inserting a new user row.
 * Most fields are optional (they have DB defaults), but username, email,
 * passwordHash, and displayName are required.
 */
export type NewUser = typeof users.$inferInsert;
