/**
 * lib/mailer.ts — Nodemailer transporter and outbound email helpers.
 *
 * This module owns all email-sending logic for Gratonite. Every type of
 * outbound email (verification, password reset, notifications) gets its own
 * named helper function below the generic `sendMail` primitive.
 *
 * Configuration (via environment variables):
 *   SMTP_HOST  — SMTP server hostname (e.g. smtp.sendgrid.net)
 *   SMTP_PORT  — SMTP port (default 587 for STARTTLS, 465 for SMTPS)
 *   SMTP_USER  — SMTP auth username
 *   SMTP_PASS  — SMTP auth password
 *   SMTP_FROM  — The "From" address shown to recipients
 *
 * For local development, point these at Mailhog (SMTP port 1025,
 * web UI at http://localhost:8025) or Mailtrap.
 *
 * Why nodemailer?
 *   It supports every common SMTP scenario out of the box, has strong TypeScript
 *   types, and doesn't lock us into any particular email service provider.
 */

import nodemailer from 'nodemailer';

// ---------------------------------------------------------------------------
// Transporter
// ---------------------------------------------------------------------------

/**
 * Singleton nodemailer transporter.
 *
 * Created once at module load time so the TCP connection can be reused across
 * multiple emails (SMTP connection pooling). The `createTransport` call is
 * synchronous and never throws — connection failures surface only when
 * `sendMail` is called.
 */
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT) || 587,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

// ---------------------------------------------------------------------------
// Generic send primitive
// ---------------------------------------------------------------------------

interface SendMailOptions {
  /** Recipient email address */
  to: string;
  /** Email subject line */
  subject: string;
  /** Full HTML body. Plain-text fallback is not currently generated. */
  html: string;
}

/**
 * sendMail — Low-level send wrapper.
 *
 * All higher-level email helpers in this file delegate to this function.
 * Throws if the SMTP transport fails — callers should catch and decide whether
 * to retry or surface the error.
 *
 * @param options - Recipient, subject, and HTML body.
 */
export async function sendMail({ to, subject, html }: SendMailOptions): Promise<void> {
  await transporter.sendMail({
    from: process.env.SMTP_FROM || 'noreply@gratonite.chat',
    to,
    subject,
    html,
  });
}

// ---------------------------------------------------------------------------
// Email verification helper
// ---------------------------------------------------------------------------

/**
 * sendVerificationEmail — Sends a branded HTML email containing a one-click
 * email verification link.
 *
 * The link format is:
 *   `${appUrl}/app/verify?token=${token}&email=${encodeURIComponent(to)}`
 *
 * The frontend at that URL is responsible for extracting the query params and
 * POSTing them to POST /api/v1/auth/verify-email/confirm.
 *
 * @param to     - The recipient's email address (the one being verified).
 * @param token  - The raw (unhashed) verification token. This is a 64-char
 *                 hex string generated by `crypto.randomBytes(32)`. It is
 *                 embedded directly in the URL — the server hashes it before
 *                 comparing to the DB, so this value is safe to send in email.
 * @param appUrl - The base URL of the frontend application, e.g.
 *                 "https://gratonite.chat". No trailing slash.
 *
 * Why send the raw token in the email rather than the hash?
 *   The token is a one-time secret. The email is the secure channel. Only the
 *   recipient can access it. On the server side we store the hash so that
 *   even if the DB is compromised an attacker can't reuse stored hashes.
 */
export async function sendVerificationEmail(
  to: string,
  token: string,
  appUrl: string
): Promise<void> {
  // Build the full verification URL that the user clicks.
  const verifyUrl = `${appUrl}/app/verify?token=${token}&email=${encodeURIComponent(to)}`;

  // HTML email body.
  // Inline styles are used throughout because many email clients (Gmail,
  // Outlook) strip <style> blocks and external CSS.
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Verify your Gratonite email</title>
</head>
<body style="margin:0;padding:0;background:#0f0f10;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f0f10;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="520" cellpadding="0" cellspacing="0" style="background:#1a1b1e;border-radius:12px;overflow:hidden;max-width:520px;width:100%;">

          <!-- Header -->
          <tr>
            <td style="background:#5865f2;padding:32px 40px;text-align:center;">
              <h1 style="margin:0;color:#ffffff;font-size:24px;font-weight:700;letter-spacing:-0.5px;">
                Gratonite
              </h1>
              <p style="margin:6px 0 0;color:#c3c8ff;font-size:14px;">
                Your place to hang out
              </p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:40px;">
              <h2 style="margin:0 0 16px;color:#ffffff;font-size:20px;font-weight:600;">
                Verify your email address
              </h2>
              <p style="margin:0 0 24px;color:#a0a3b1;font-size:15px;line-height:1.6;">
                Thanks for signing up! Click the button below to verify your email
                address and activate your account. This link expires in
                <strong style="color:#ffffff;">24 hours</strong>.
              </p>

              <!-- CTA button -->
              <table cellpadding="0" cellspacing="0" style="margin:0 0 32px;">
                <tr>
                  <td style="border-radius:8px;background:#5865f2;">
                    <a href="${verifyUrl}"
                       style="display:inline-block;padding:14px 32px;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;border-radius:8px;">
                      Verify Email Address
                    </a>
                  </td>
                </tr>
              </table>

              <!-- Fallback URL -->
              <p style="margin:0 0 8px;color:#a0a3b1;font-size:13px;">
                If the button doesn't work, copy and paste this link into your browser:
              </p>
              <p style="margin:0;word-break:break-all;">
                <a href="${verifyUrl}" style="color:#5865f2;font-size:13px;">${verifyUrl}</a>
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:24px 40px;border-top:1px solid #2c2d32;">
              <p style="margin:0;color:#5a5c6a;font-size:12px;line-height:1.6;">
                You received this email because an account was created on Gratonite
                using this address. If you didn't sign up, you can safely ignore
                this email — your inbox will not receive further messages from us.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();

  await sendMail({
    to,
    subject: 'Verify your Gratonite email address',
    html,
  });
}
